shared:
    image: node:8

parameters:
  p1: p1

jobs:
    main:
        template: sd/noop
        requires: [~pr, ~commit]
        steps:
        - export: export GREETING="Hello, world!"
        - hello: echo $GREETING
    a:
        requires: [~pr, ~commit]
        steps:
        - export: export GREETING="Hello, world!"
        - hello: echo $GREETING
    b:
        requires: [~pr, ~commit]
        steps:
        - export: export GREETING="Hello, world!"
        - hello: echo $GREETING
    c:
        requires: [~pr, ~commit]
        steps:
        - export: export GREETING="Hello, world!"
        - hello: echo $GREETING
    j:
        steps:
        - export: export GREETING="Hello, world!"
        - hello: echo $GREETING
